<a href="https://colab.research.google.com/github/MakarevichDE/PDA_SOL/blob/main/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_3_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [34]:
a = 28
b = 7
y = 3
o = 1
u = 1
v = 5

Задание 1.

In [35]:
A2 = np.matrix([[2, 3+a, 4-u],
               [b, y, v],
               [5, 10*u, -2]])
A2

matrix([[ 2, 31,  3],
        [ 7,  3,  5],
        [ 5, 10, -2]])

In [36]:
B2 = np.matrix([[b, -3, 4+u],
               [a, 4, v],
               [5*u, 10, -2]])
B2

matrix([[ 7, -3,  5],
        [28,  4,  5],
        [ 5, 10, -2]])

In [7]:
C = np.matrix([[-1, 3+u, 4-v],
               [2, 1, v],
               [5, 5-u, -2]])
C

matrix([[-1,  4, -1],
        [ 2,  1,  5],
        [ 5,  4, -2]])

In [37]:
A2*B2*C

matrix([[ 194, 4372, -475],
        [ 124,  833,  -33],
        [ 100, 1541, -438]])

Задание 2.

In [10]:
G = np.matrix([[2, 3+a, 4+u, 6],
               [b+1, y, v, 12],
               [5, -2, 16, u+1],
               [2, 7, 11, -6]])
G

matrix([[ 2, 31,  5,  6],
        [ 8,  3,  5, 12],
        [ 5, -2, 16,  2],
        [ 2,  7, 11, -6]])

In [11]:
np.linalg.det(G)

19980.000000000015

In [12]:
np.linalg.eig(G)

(array([ 25.94652312, -16.43073489,  -4.63253307,  10.11674485]),
 matrix([[ 0.76142326,  0.76536537,  0.86687989,  0.78549332],
         [ 0.48096506, -0.4987647 , -0.06815044,  0.31301642],
         [ 0.34039116, -0.1715045 , -0.1718026 , -0.5198864 ],
         [ 0.27026117,  0.36883036, -0.4629888 , -0.12140471]]))

In [13]:
Ginv = np.linalg.inv(G)
Ginv

matrix([[-0.0976977 ,  0.22282282, -0.22642643,  0.27247247],
        [ 0.02492492,  0.0036036 , -0.02522523,  0.02372372],
        [ 0.02772773, -0.06426426,  0.11651652, -0.06196196],
        [ 0.04734735, -0.03933934,  0.10870871, -0.16176176]])

Задание 3.

In [14]:
A1 = np.matrix([[2, -5, 7],
               [8, 1, 9],
               [3, -4, 12]])
A1

matrix([[ 2, -5,  7],
        [ 8,  1,  9],
        [ 3, -4, 12]])

In [17]:
C1 = np.matrix([[-25, -17, 78],
               [11, 89, 76],
               [-5, 24, 115]])
C1

matrix([[-25, -17,  78],
        [ 11,  89,  76],
        [ -5,  24, 115]])

In [18]:
B1 = np.linalg.solve(A1, C1)
B1

matrix([[-3.,  4.,  1.],
        [ 8., 12., -4.],
        [ 3.,  5.,  8.]])

In [19]:
A1*B1

matrix([[-25., -17.,  78.],
        [ 11.,  89.,  76.],
        [ -5.,  24., 115.]])

Задание 4.

In [38]:
Y = np.matrix([[3, 1, 1, y],
               [1, -u, v, 4],
               [-5, 0, -1, -7],
               [1, -6, a, 6]])
Y

matrix([[ 3,  1,  1,  3],
        [ 1, -1,  5,  4],
        [-5,  0, -1, -7],
        [ 1, -6, 28,  6]])

In [39]:
Z = np.matrix([[a], [b], [-5], [3]])
Z

matrix([[28],
        [ 7],
        [-5],
        [ 3]])

In [40]:
X = np.linalg.solve(Y, Z)
X

matrix([[-3.70967742],
        [26.03225806],
        [ 5.25806452],
        [ 2.61290323]])

In [41]:
Y*X

matrix([[28.],
        [ 7.],
        [-5.],
        [ 3.]])