<a href="https://colab.research.google.com/github/MakarevichDE/PDA_SOL/blob/main/%D0%A1%D0%B0%D0%BC%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Самостоятельная работа 2. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [23]:
import numpy as np

np.__version__

'1.23.5'

2) Создать нулевой вектор размера 10

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [ ]:
np.full(7,7)

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
np.arange(10,101,2)

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [24]:
a=np.random.random((5,5))
a

array([[0.68067804, 0.30275999, 0.77133003, 0.32811166, 0.39563787],
       [0.11389493, 0.36279208, 0.0084689 , 0.84678798, 0.73585613],
       [0.46398658, 0.82395031, 0.29136385, 0.4833218 , 0.01836854],
       [0.24391266, 0.12612114, 0.0692199 , 0.01796883, 0.80301962],
       [0.13456092, 0.36668222, 0.87295933, 0.64345896, 0.71309091]])

In [25]:
a[::-1]

array([[0.13456092, 0.36668222, 0.87295933, 0.64345896, 0.71309091],
       [0.24391266, 0.12612114, 0.0692199 , 0.01796883, 0.80301962],
       [0.46398658, 0.82395031, 0.29136385, 0.4833218 , 0.01836854],
       [0.11389493, 0.36279208, 0.0084689 , 0.84678798, 0.73585613],
       [0.68067804, 0.30275999, 0.77133003, 0.32811166, 0.39563787]])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
np.eye(4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
b=np.full((4,4),7)
b -= np.diag([6,5,4,3])
print(b)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
c=np.zeros((5,5))
c += np.arange(0,5)
c

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
d=np.random.random((10,10))
print('Исходный массив: \n',d)
e=d.mean(axis=1, keepdims=True)
print('Среднее по строкам: \n',e)
d -=e
print('Результат: \n',d)

Исходный массив: 
 [[0.44630169 0.05669533 0.39387022 0.43362825 0.15034457 0.08202057
  0.75789437 0.3124131  0.97505305 0.04011043]
 [0.30818326 0.77897629 0.08277843 0.91409789 0.00272426 0.0947696
  0.45362105 0.209516   0.3078061  0.12536951]
 [0.82599405 0.24165165 0.37593817 0.29208637 0.79684948 0.11302765
  0.7487232  0.0812232  0.24167595 0.24804473]
 [0.22701215 0.66286825 0.14312814 0.27347394 0.80695136 0.88628321
  0.83582496 0.93770446 0.02331264 0.7320748 ]
 [0.03126226 0.75088235 0.37537698 0.97195239 0.33460738 0.4049001
  0.58454102 0.97175909 0.26413469 0.65792785]
 [0.00705773 0.84769242 0.28016425 0.83591961 0.69027237 0.57803543
  0.09142772 0.10162618 0.52943554 0.75980564]
 [0.84305713 0.41543245 0.04923805 0.46200074 0.04943599 0.60410237
  0.3442854  0.00105707 0.7998308  0.60123687]
 [0.89816105 0.24837114 0.73385239 0.37583883 0.22457814 0.01895872
  0.2732454  0.79331858 0.22047079 0.26363186]
 [0.51667601 0.61248343 0.9081155  0.96684975 0.87476255 0.8949

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [ ]:
d=np.random.random((10,10))
print('Исходный массив: \n',d)
e=np.median(d,axis=0, keepdims=True)
print('Медиана по столбцам: \n',e)
d -=e
print('Результат: \n',d)

Исходный массив: 
 [[0.46579443 0.50305077 0.00755673 0.97877616 0.07111426 0.35558927
  0.92371704 0.59008153 0.09348275 0.07755513]
 [0.18557613 0.22522989 0.48606723 0.08706451 0.97302323 0.54647776
  0.91606366 0.31863482 0.01823774 0.68128452]
 [0.55317295 0.84607041 0.45005659 0.48813499 0.11373986 0.21854824
  0.33360419 0.55955489 0.65643159 0.26529138]
 [0.52971535 0.43513739 0.7768269  0.84060322 0.75818738 0.02233104
  0.45928292 0.28342141 0.03630399 0.86162685]
 [0.91507119 0.14025135 0.69488742 0.09094117 0.18389784 0.96173403
  0.71788825 0.40469926 0.30515599 0.82524681]
 [0.65529285 0.74258484 0.65410727 0.12663548 0.2999513  0.16622836
  0.11420795 0.03021118 0.90605269 0.01223083]
 [0.01774504 0.4518168  0.08212872 0.52659749 0.04545371 0.75120215
  0.3079293  0.69828958 0.37607949 0.00718971]
 [0.09515406 0.38906503 0.26165966 0.92226029 0.87051395 0.61465335
  0.90176289 0.38261078 0.79826072 0.05311581]
 [0.17827449 0.66340168 0.68536065 0.04309862 0.20782262 0.77

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбцы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [ ]:
d=np.random.random((5,5))
print('Исходный массив: \n',d)
e=d.max(axis=1, keepdims=True)
f=d.min(axis=1,keepdims=True)
print('Результат: \n',np.hstack((d,e,f)))

Исходный массив: 
 [[0.20669991 0.82018734 0.14477167 0.46761448 0.19075592]
 [0.26493525 0.29883792 0.25261224 0.97105428 0.70087949]
 [0.32067009 0.31614596 0.8884301  0.35727432 0.43459749]
 [0.43786804 0.62648034 0.64626731 0.94808905 0.58962181]
 [0.63599683 0.95519663 0.05858024 0.33022912 0.38959375]]
Результат: 
 [[0.20669991 0.82018734 0.14477167 0.46761448 0.19075592 0.82018734
  0.14477167]
 [0.26493525 0.29883792 0.25261224 0.97105428 0.70087949 0.97105428
  0.25261224]
 [0.32067009 0.31614596 0.8884301  0.35727432 0.43459749 0.8884301
  0.31614596]
 [0.43786804 0.62648034 0.64626731 0.94808905 0.58962181 0.94808905
  0.43786804]
 [0.63599683 0.95519663 0.05858024 0.33022912 0.38959375 0.95519663
  0.05858024]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу этого произведения.  

In [ ]:
z=np.arange(1,52)
print(z)
h=z[z % 2 != 0]
h=h[0:25].reshape(5,5)
print(h)
i=z[z % 2 == 0].reshape(5,5)
print(i)
o=h.dot(i)
print('Произведение матриц: \n',o)
print('Обратная матрица не может быть построена, потому что определитель равен 0: ',np.linalg.det(o))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51]
[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]
Произведение матриц: 
 [[ 750  800  850  900  950]
 [1850 2000 2150 2300 2450]
 [2950 3200 3450 3700 3950]
 [4050 4400 4750 5100 5450]
 [5150 5600 6050 6500 6950]]
Обратная матрица не может быть построена, потому что определитель равен 0:  0.0


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [ ]:
k = np.zeros((8,8),dtype=int)
k[1::2,::2] = 1 #нечетные элементы каждой второй строки
k[::2,1::2] = 1 #нечетные элементы каждого второго столбца
print(k)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
